### ISSUE TITLE
Manually Clone Google Test

### ISSUE THREAD

**Issue by conorcaseyc** [libtangle/tools#1]
Hello.

I am presuming you already know this, but, when you clone the repository from GitHub, the gtest folder in the test folder is empty. You then need to manually clone [Google Test](https://github.com/google/googletest) and paste the contents into the gtest folder for the library to build. 

Also, how do you interact with the library? For example, how would I utilise a Hadamard gate in the software? 

Good luck at the European Union Competition for Young Scientists!

**Comment by conorcaseyc** [comment]
Never mind, I figured out how to utilise it.

**Comment by adamisntdead** [comment]
Hey! This is a big rewrite and is unfinished, I am porting previous code. I will have propper usage information when it's heading towards finished.

As for Google Test, you don't need to clone - it uses git submodules. That means that I won't have to look after the google test code, it just gets it from GitHub.

Thanks!

**Comment by conorcaseyc** [comment]
Hi.

Thanks for the reply. Sorry I was completely unaware that this was still in active development. Good luck with it.

**Comment by conorcaseyc** [comment]
Maybe, it is just a weird glitch on my system, but, I had to manually clone Google Test to get it to work.
